#!/usr/bin/bash

rsync --exclude 'env' --safe-links --exclude '.git' --exclude 'data' --exclude 'dnase' --exclude 'scATAC'  --max-size 10m -rv ~/Harnett/Atac_evo/ /g/furlong/project/28_B_DNASE/analysis/evolutionary_analyses/INSIGHT/

