#!/usr/bin/bash

rsync --safe-links --exclude 'env' --exclude '.git' --exclude 'data' --exclude 'dnase' --exclude 'scATAC'  --max-size 10m -rv /g/furlong/project/28_B_DNASE/analysis/evolutionary_analyses/INSIGHT/ ~/Harnett/Atac_evo/

ln -s /g/furlong/project/28_B_DNASE/analysis/evolutionary_analyses/INSIGHT/data ~/Harnett/Atac_evo/data
ln -s /g/furlong/project/28_B_DNASE/analysis/evolutionary_analyses/INSIGHT/dnase ~/Harnett/Atac_evo/dnase
ln -s /g/furlong/project/28_B_DNASE/analysis/evolutionary_analyses/INSIGHT/scATAC/ ~/Harnett/Atac_evo/scATAC
